print("______________________________________________________")
a=float(input("enter the bill amount:"))
print("______________________________________________________")
print(a)
b=float(input("enter the tip percentage:"))
print("______________________________________________________")
print(b)
print("______________________________________________________")
e=(a*b/100)
print(e)
c=int(input("enter the number of persons:"))
per_person=(e/c)
print(f'tip per person: {per_person}')
total_amount=(a+e)
print(f'total amount: {total_amount}')